routes/web.php
<?php
//Route::redirect('/', '/admin/home');
Route::get('/', function () { return view('welcome'); });
Auth::routes(['register' => false]);

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::delete('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::delete('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');
    Route::resource('purohits', 'Admin\PurohitsController');
    Route::delete('purohits_mass_destroy', 'Admin\PurohitsController@massDestroy')->name('purohits.mass_destroy');
});

app/Purohit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Purohit extends Model
{
    protected $fillable = ['name', 'mobile', 'profile_image', 'grade','date_of_birth'];
}

app/Http/Controllers/Admin/PurohitsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Purohit;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Gate;

class PurohitsController extends Controller
{
    public function index()
    {
    	$purohits = Purohit::all();

    	return view('admin.purohits.index', compact('purohits'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $purohit = Purohit::find($id);
        return view('admin.purohits.show', compact('purohit'));
    }

    /**
     * Show the form for creating a new purohit.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.purohits.create');
    }

    /**
     * Store a newly created purohit in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $request->validate([
        //   'namaSiswa' => 'required',
        //   'alamatSiswa' => 'required'
        // ]);

        Purohit::create($request->all());
        return redirect()->route('admin.purohits.index')
                        ->with('success', 'New purohit created successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $purohit = Purohit::find($id);
        return view('admin.purohits.edit', compact('purohit'));
    }

    /**
     * Update Purohit in storage.
     *
     * @param  \App\Http\Requests\UpdateUsersRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Purohit $purohit)
    {

        $purohit->update($request->all());

        return redirect()->route('admin.purohits.index')
                        ->with('success', 'Purohit updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $purohit = Purohit::find($id);
        $purohit->delete();
        return redirect()->route('admin.purohits.index')
                        ->with('success', 'Purohit deleted successfully');
    }

     /**
     * Delete all selected Purohit at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        
        Purohit::whereIn('id', request('ids'))->delete();

        return response()->noContent();
    }
}

resources/views/admin/purohits/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.purohit.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.purohits.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('cruds.purohit.fields.name') }}*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($purohit) ? $purohit->name : '') }}" required>
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.purohit.fields.name_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('mobile') ? 'has-error' : '' }}">
                <label for="mobile">{{ trans('cruds.purohit.fields.mobile') }}*</label>
                <input type="text" id="mobile" name="mobile" class="form-control" value="{{ old('mobile', isset($purohit) ? $purohit->mobile : '') }}" required>
                @if($errors->has('mobile'))
                    <em class="invalid-feedback">
                        {{ $errors->first('mobile') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.purohit.fields.mobile_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('profile_image') ? 'has-error' : '' }}">
                <label for="profile_image">{{ trans('cruds.purohit.fields.profile_image') }}*</label>
                <input type="file" id="profile_image" name="profile_image" class="form-control" value="{{ old('profile_image', isset($purohit) ? $purohit->profile_image : '') }}" required>
                @if($errors->has('profile_image'))
                    <em class="invalid-feedback">
                        {{ $errors->first('profile_image') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.purohit.fields.profile_image_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('grade') ? 'has-error' : '' }}">
                <label for="grade">{{ trans('cruds.purohit.fields.grade') }}*</label>
                <input type="text" id="grade" name="grade" class="form-control" value="{{ old('grade', isset($purohit) ? $purohit->grade : '') }}" required>
                @if($errors->has('grade'))
                    <em class="invalid-feedback">
                        {{ $errors->first('grade') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.purohit.fields.grade_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('date_of_birth') ? 'has-error' : '' }}">
                <label for="date_of_birth">{{ trans('cruds.purohit.fields.date_of_birth') }}*</label>
                <input type="text" id="date_of_birth" name="date_of_birth" class="form-control" value="{{ old('date_of_birth', isset($purohit) ? $purohit->date_of_birth : '') }}" required>
                @if($errors->has('date_of_birth'))
                    <em class="invalid-feedback">
                        {{ $errors->first('date_of_birth') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.purohit.fields.grade_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>


    </div>
</div>
@endsection

resources/views/admin/purohits/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.purohit.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.purohits.update", [$purohit->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('cruds.purohit.fields.name') }}*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($purohit) ? $purohit->name : '') }}" required>
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.purohit.fields.name_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('mobile') ? 'has-error' : '' }}">
                <label for="mobile">{{ trans('cruds.purohit.fields.mobile') }}*</label>
                <input type="mobile" id="mobile" name="mobile" class="form-control" value="{{ old('mobile', isset($purohit) ? $purohit->mobile : '') }}" required>
                @if($errors->has('mobile'))
                    <em class="invalid-feedback">
                        {{ $errors->first('mobile') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.purohit.fields.mobile_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('grade') ? 'has-error' : '' }}">
                <label for="grade">{{ trans('cruds.purohit.fields.grade') }}*</label>
                <input type="grade" id="grade" name="grade" class="form-control" value="{{ old('grade', isset($purohit) ? $purohit->grade : '') }}" required>
                @if($errors->has('grade'))
                    <em class="invalid-feedback">
                        {{ $errors->first('grade') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.purohit.fields.grade_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('date_of_birth') ? 'has-error' : '' }}">
                <label for="date_of_birth">{{ trans('cruds.purohit.fields.date_of_birth') }}*</label>
                <input type="date_of_birth" id="date_of_birth" name="date_of_birth" class="form-control" value="{{ old('date_of_birth', isset($purohit) ? $purohit->date_of_birth : '') }}" required>
                @if($errors->has('date_of_birth'))
                    <em class="invalid-feedback">
                        {{ $errors->first('date_of_birth') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.purohit.fields.date_of_birth_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>


    </div>
</div>
@endsection

resources/views/admin/purohits/index.blade.php
@extends('layouts.admin')
@section('content')
<div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.purohits.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.purohit.title_singular') }}
            </a>
        </div>
    </div>
    @if ($message = Session::get('success'))
      <div class="alert alert-success">
        <p>{{$message}}</p>
      </div>
    @endif
<div class="card">
    <div class="card-header">
        Purohit List
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Purohit" style="margin-left: 0px; width: 100%;">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            ID
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Mobile
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($purohits as $key => $purohit)
                        <tr data-entry-id="{{ $purohit->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $purohit->id ?? '' }}
                            </td>
                            <td>
                                {{ $purohit->name ?? '' }}
                            </td>
                            <td>
                                {{ $purohit->mobile ?? '' }}
                            </td>
                            <td>
                                <a class="btn btn-xs btn-primary" href="{{ route('admin.purohits.show', $purohit->id) }}">
                                    {{ trans('global.view') }}
                                </a>

                                <a class="btn btn-xs btn-info" href="{{ route('admin.purohits.edit', $purohit->id) }}">
                                    {{ trans('global.edit') }}
                                </a>

                                <form action="{{ route('admin.purohits.destroy', $purohit->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                </form>

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>


    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.purohits.mass_destroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Purohit:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/purohits/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.purohit.title') }}
    </div>

    <div class="card-body">
        <div class="mb-2">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.purohit.fields.id') }}
                        </th>
                        <td>
                            {{ $purohit->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.purohit.fields.name') }}
                        </th>
                        <td>
                            {{ $purohit->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.purohit.fields.mobile') }}
                        </th>
                        <td>
                            {{ $purohit->mobile }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.purohit.fields.grade') }}
                        </th>
                        <td>
                            {{ $purohit->grade }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.purohit.fields.date_of_birth') }}
                        </th>
                        <td>
                            {{ $purohit->date_of_birth }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <a style="margin-top:20px;" class="btn btn-default" href="{{ url()->previous() }}">
                {{ trans('global.back_to_list') }}
            </a>
        </div>


    </div>
</div>
@endsection